### ISSUE TITLE
Помощь с Web-частью

### ISSUE THREAD

**Issue by fserg** [ripreal/V8LogScannerWeb#1]
Привет.
Хотел бы помочь с web-частью.
Но я не совсем понимаю, как сейчас это реализовано.
V8LogScannerWeb - сейчас это JS-фронт, который как-то умеет управлять [консольной утилитой](https://github.com/ripreal/V8LogScanner)?

А никак не сделать чтобы основной проект предоставлял какой-то REST для запуска парсинга файлов?
Если такое возможно, то я бы красиый фронт на реакте сделал.

P.S. сам 1Сник, но изучаю активно JS

**Comment by ripreal** [comment]
Привет,  буду рад помощи, и да, я сам не профи.

V8LogScannerWEB состоит из фронта на javascript-е, бакенда на java (spring) и самой jar-core библиотеки V8LogScanner.

 Взаимодействие между фронтом и бакендом работает исключительно, как ты правильно предположил, через REST. Причем REST интерфейс готов более чем на половину. Смотри его реализацию здесь https://github.com/ripreal/V8LogScannerWeb/blob/master/trunk/src/main/java/org/v8LogScanner/webLayer/webAppControllers/RESTClient.java

Сейчас исходники не компилируются, но я планирую все починить в ближайшее время и тогда можно будет самому потрогать как это сейчас работает.  Если есть интерес, то давай присоединяйся, я опишу все подробнее.

**Comment by fserg** [comment]
Супер!
Тогда я тогда накидаю пока что-то типа mockup-server глядя на исходники.
И постараюсь в выходные что-нибудь сделать на React.

**Comment by ripreal** [comment]
Нужно подумать о том, как можно объединить react и java на фреймворке Spring.  Java spring использует maven как билд систему, HSQL как СУБД,  и  tomcat как HTTP - сервер.
React естественно, это node.js и yarn - совсем другие технологиии.

Хотелось бы чтобы все приложение стартовало из одного файла. 

С одной стороны я могу скомпилировать весь бакенд проект в одну jar либу. Он сможет стартовать веб-сервер Tomcat, REST-интерфейс, а также  js и html странички. Но React вряд ли она сможет запустить. Соответственно, это будет две запускали. Одна для запуска React, а другая для запуска Java?  Это не очень удобно.

МОжет пойти другим путем и превратить это проект в сервис, который хостить на amazon web services? Изучить AWS ьбудет очень, очень полезно. Тем боеле у меня уже есть аккаунт.

Ещё посмотри интерфейс  консольной утилиты V8LogScanner, это тебе даст представление, какой лучше всего сделать интерфейс.

**Comment by fserg** [comment]
Первая мысль тоже была про отдельный web-сервис.
Но потом подумал, что вряд ли этот будет востребованно.
Ведь кто потребители такого сервиса? Это другие разработчики. Мне кажется большинство захотят свой standalone и чтобы все бесплатно. (на AWS'е не получится бесплатно)

React можно сделать Electron приложением и, может быть, я смогу внутри него jar'ник запускать.

Я не отказываюсь от идеи сервиса - это прикольно сделать даже чисто ради опыта.

**Comment by ripreal** [comment]
Ок, согласен, не каждый захочет грузит 1 гб логов с локальной машины в сервис. Но я думаю все равно нужно будет где-нибудь опубликовать, раз уж будет веб-оболочка, хотя бы для 
1. Continious integration, чтобы после коммита, можно было увидеть сразу результат
2. Демо возможностей.

**Comment by ripreal** [comment]
Добавил чат https://gitter.im/V8LogScannerWeb/Lobby?source=orgpage
